version: '3.3'
services:
  mongodb:
    image: mongo:4.4.14
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P4ssword2022
    volumes:
      - mongodb-volume:/data/db
volumes:
  mongodb-volume:
    external: false
